In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch
import src.modules as module
from src.optimizer import SGD
from src.functional import generate_disc_set
import math

In [3]:
torch.set_grad_enabled(False)

## Generate Dataset

In [27]:
N = 12
train_input, train_target = generate_disc_set(N, batch_size=3)
test_input, test_target = generate_disc_set(N , batch_size=3)

In [29]:
print(train_input.shape)
print(train_target.shape)
print(train_input[0])
print(train_target[0])

torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
tensor([[0.0517, 0.3338],
        [0.7798, 0.6022],
        [0.5270, 0.8882]])
tensor([[1., 0.],
        [0., 1.],
        [0., 1.]])


In [30]:
#testing sequential, tanh, linear, relu
model = module.Sequential(('lin1',module.Linear(2,5)),('relu1',module.ReLU()),('lin2',module.Linear(5,2)))
optim = SGD(model.parameters(), lr=0.01)
print(model[1].name)
print(model(train_input[1]))
print(train_target[1])

relu1
tensor([[-0.2319, -0.1754],
        [-0.1805, -0.1795],
        [-0.2627, -0.1756]])
tensor([[0., 1.],
        [0., 1.],
        [0., 1.]])


In [36]:
loss = module.LossMSE()
out = model(train_input[1])
print(out)
print(loss(out, train_target[1]))
d_loss = loss.backward(out,train_target[1])
print(d_loss)
model.backward(d_loss)



tensor([[-0.2319, -0.1754],
        [-0.1805, -0.1795],
        [-0.2627, -0.1756]])
tensor(0.7183)
tensor([[-0.4639, -2.3507],
        [-0.3610, -2.3589],
        [-0.5254, -2.3512]])
Gradient wrt to input output of module lin2 tensor([[-0.3247,  0.2724,  0.0958,  0.2669, -0.8494],
        [-0.3023,  0.2616,  0.0637,  0.2628, -0.8271],
        [-0.3386,  0.2794,  0.1150,  0.2700, -0.8644]])
Gradient wrt to input output of module relu1 tensor([[-0.0000, 0.0000, 0.0958, 0.2669, -0.0000],
        [-0.0000, 0.0000, 0.0637, 0.2628, -0.0000],
        [-0.0000, 0.0000, 0.1150, 0.2700, -0.0000]])
Gradient wrt to input output of module lin1 tensor([[-0.0445,  0.1063],
        [-0.0277,  0.0961],
        [-0.0545,  0.1125]])


tensor([[-0.0445,  0.1063],
        [-0.0277,  0.0961],
        [-0.0545,  0.1125]])

In [ ]:
def train(inp, target, model, optim, epochs):
    for i in range(epochs):
        print("Epoch {0}".format(i))
        out = model(inputs)
        print("Out {0}".format(out))
        print("Loss {0}".format(loss(out, target)))
        optim.zero_grad()
        d_loss = loss.backward(out, target)
        model.backward(d_loss)
        optim.step()
    

In [ ]:
train(inputs, torch.Tensor([[0.8,0.2]]), model, optim, 10)